---
title: "ACrep_Results.Rmd"
author: "Hannah Moshontz"
date: "Last Updated `r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

## Purpose

This script generates text for the results section of the ACREP / PSA004 Stage 2 RRR. It also runs the analysis .Rmd.


# Run the analysis script

```{r, child = '../05_Analysis/ACrep_Analysis_V2.Rmd'}
```

# Method

## Participants

```{r}
#create dataset for demographics
final_demographics <- final_long %>% 
  group_by(id) %>%
  slice(1) %>% 
  ungroup() %>% 
  select(id, 
         contains("exclusion"),
         survey_lang,
         turk,
         language,
         lab_id, 
         lab_country,
         country,
         UN_Region,
         gender, 
         gender_other,
         starts_with("ethn_"),
         education,
         education_level,
         starts_with("comp"),
         birth_country,
         case,
         age)

#error out if count doesn't match
if (length(unique(final_long$id)) != nrow(final_demographics)) STOP

```

Questions
- What is 'Person' (35 unique values)
- What is 'case'

Participants were 
